export const GAME_CREATE_REQUEST = "GAME_CREATE_REQUEST";
export const GAME_CREATE_SUCCESS = "GAME_CREATE_SUCCESS";
export const GAME_CREATE_FAIL = "GAME_CREATE_FAIL";

export const GAME_LIST_MY_REQUEST = "GAME_LIST_MY_REQUEST";
export const GAME_LIST_MY_SUCCESS = "GAME_LIST_MY_SUCCESS";
export const GAME_LIST_MY_FAIL = "GAME_LIST_MY_FAIL";
export const GAME_LIST_MY_RESET = "GAME_LIST_MY_RESET";

export const GAME_LIST_REQUEST = "GAME_LIST_REQUEST";
export const GAME_LIST_SUCCESS = "GAME_LIST_SUCCESS";
export const GAME_LIST_FAIL = "GAME_LIST_FAIL";
