export const TRANSACTION_CREATE_REQUEST = "TRANSACTION_CREATE_REQUEST";
export const TRANSACTION_CREATE_SUCCESS = "TRANSACTION_CREATE_SUCCESS";
export const TRANSACTION_CREATE_FAIL = "TRANSACTION_CREATE_FAIL";

export const TRANSACTION_LIST_MY_REQUEST = "TRANSACTION_LIST_MY_REQUEST";
export const TRANSACTION_LIST_MY_SUCCESS = "TRANSACTION_LIST_MY_SUCCESS";
export const TRANSACTION_LIST_MY_FAIL = "TRANSACTION_LIST_MY_FAIL";
export const TRANSACTION_LIST_MY_RESET = "TRANSACTION_LIST_MY_RESET";

export const TRANSACTION_LIST_REQUEST = "TRANSACTION_LIST_REQUEST";
export const TRANSACTION_LIST_SUCCESS = "TRANSACTION_LIST_SUCCESS";
export const TRANSACTION_LIST_FAIL = "TRANSACTION_LIST_FAIL";
