# Generated by Django 4.1.4 on 2022-12-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('character', models.CharField(max_length=50)),
                ('element_type', models.CharField(choices=[('P', 'Pyro'), ('H', 'Hydro'), ('D', 'Dendro'), ('A', 'Anemo'), ('C', 'Cryo'), ('E', 'Electro')], max_length=1)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
            ],
        ),
    ]
