# Generated by Django 4.1.4 on 2023-01-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='character',
            field=models.CharField(choices=[('Albedo', 'Albedo'), ('Aloy', 'Aloy'), ('Amber', 'Amber'), ('Ayaka', 'Ayaka'), ('Ayato', 'Ayato'), ('Barbara', 'Barbara'), ('Beidou', 'Beidou'), ('Bennet', 'Bennet'), ('Candace', 'Candace'), ('Childe', 'Childe'), ('Chongyun', 'Chongyun'), ('Collei', 'Collei'), ('Cyno', 'Cyno'), ('Diluc', 'Diluc'), ('Diona', 'Diona'), ('Dori', 'Dori'), ('Eula', 'Eula'), ('Fischl', 'Fischl'), ('Gorou', 'Gorou'), ('shikanoin-heizou', 'Heizou'), ('Hu-Tao', 'Hutao'), ('Arataki-Itto', 'Itto'), ('Jean', 'Jean'), ('Kaeya', 'Kaeya'), ('Kazuha', 'Kazuha'), ('Keqing', 'Keqing'), ('Klee', 'Klee'), ('kuki-shinobu', 'Kuki'), ('Layla', 'Layla'), ('Lisa', 'Lisa'), ('Mona', 'Mona'), ('Nahida', 'Nahida'), ('Nilou', 'Nilou'), ('Ningguang', 'Ningguang'), ('Noelle', 'Noelle'), ('Qiqi', 'Qiqi'), ('Raiden', 'Raiden'), ('Razor', 'Razor'), ('Rosaria', 'Rosaria'), ('Sara', 'Sara'), ('Sayu', 'Sayu'), ('Shenhe', 'Shenhe'), ('Sucrose', 'Sucrose'), ('Tartaglia', 'Tartaglia'), ('Thoma', 'Thoma'), ('Tighnari', 'Tighnari'), ('Venti', 'Venti'), ('Xiangling', 'Xiangling'), ('Xiao', 'Xiao'), ('Xingqiu', 'Xingqiu'), ('Xinyan', 'Xinyan'), ('Yae-Miko', 'Yaemiko'), ('Yan-Fei', 'Yanfei'), ('Yelan', 'Yelan'), ('Yoimiya', 'Yoimiya'), ('yun-jin', 'Yunjin'), ('zhongli', 'Zhongli')], default='Albedo', max_length=20),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='element_type',
            field=models.CharField(choices=[('Pyro', 'Pyro'), ('Hydro', 'Hydro'), ('Dendro', 'Dendro'), ('Anemo', 'Anemo'), ('Cryo', 'Cryo'), ('Electro', 'Electro'), ('Geo', 'Geo')], default='Pyro', max_length=10),
        ),
    ]
