# Generated by Django 4.1.4 on 2022-12-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sticker_element_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='character',
            field=models.CharField(choices=[('ALBE', 'Albedo'), ('ALOY', 'Aloy'), ('AMBE', 'Amber'), ('AYAK', 'Ayaka'), ('AYAT', 'Ayato'), ('BARB', 'Barbara'), ('BEID', 'Beidou'), ('BENN', 'Bennet'), ('CAND', 'Candace'), ('CHIL', 'Childe'), ('CHON', 'Chongyun')], default='ALBE', max_length=4),
        ),
    ]
