# Generated by Django 4.1.4 on 2022-12-30 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_remove_sticker_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_played', models.DateField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=10)),
                ('transaction_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AlterField(
            model_name='sticker',
            name='character',
            field=models.CharField(choices=[('ALBE', 'Albedo'), ('ALOY', 'Aloy'), ('AMBE', 'Amber'), ('AYAK', 'Ayaka'), ('AYAT', 'Ayato'), ('BARB', 'Barbara'), ('BEID', 'Beidou'), ('BENN', 'Bennet'), ('CAND', 'Candace'), ('CHIL', 'Childe'), ('CHON', 'Chongyun'), ('COLL', 'Collei'), ('CYNO', 'Cyno'), ('DILU', 'Diluc'), ('DION', 'Diona'), ('DORI', 'Dori'), ('EULA', 'Eula'), ('FISC', 'Fischl'), ('GORO', 'Gorou'), ('HEIZ', 'shikanoin-heizou'), ('HUTA', 'Hu-Tao'), ('ITTO', 'Arataki-Itto'), ('JEAN', 'Jean'), ('KAEY', 'Kaey'), ('KAZU', 'Kazuha'), ('KEQI', 'Keqing'), ('KLEE', 'Klee'), ('KUKI', 'kuki-shinobu'), ('LAYL', 'Layla'), ('LISA', 'Lisa'), ('MONA', 'Mona'), ('NAHI', 'Nahida'), ('NILO', 'Nilou'), ('NING', 'Ningguang'), ('NOEL', 'Noelle'), ('QIQI', 'Qiqi'), ('RAID', 'Raiden'), ('RAZO', 'Razor'), ('ROSA', 'Rosaria'), ('SARA', 'Sara'), ('SAYU', 'Sayu'), ('SHEN', 'Shenhe'), ('SUCR', 'Sucrose'), ('TART', 'Tartaglia'), ('THOM', 'Thoma'), ('TIGH', 'Tighnari'), ('VENT', 'Venti'), ('XIAN', 'Xiangling'), ('XIAO', 'Xiao'), ('XING', 'Xingqiu'), ('XINY', 'Xinyan'), ('YAEM', 'Yae-Miko'), ('YANF', 'Yan-Fei'), ('YELA', 'Yelan'), ('YOIM', 'Yoimiya'), ('YUNJ', 'yun-jin'), ('ZHON', 'zhongli')], default='ALBE', max_length=4),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wallet'),
        ),
        migrations.AddField(
            model_name='game',
            name='prize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sticker'),
        ),
    ]
