# Generated by Django 4.1.4 on 2023-01-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_player_game_user_remove_game_date_played_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='element_type',
            field=models.CharField(choices=[('P', 'Pyro'), ('H', 'Hydro'), ('D', 'Dendro'), ('A', 'Anemo'), ('C', 'Cryo'), ('E', 'Electro'), ('G', 'Geo')], default='P', max_length=1),
        ),
    ]
